export const colors = {
  // Primary styles



    border: 'hsl(var(--border))',
    input: 'hsl(var(--input))',
    ring: 'hsl(var(--ring))',
    background: 'hsl(var(--background))',
    foreground: 'hsl(var(--foreground))',
    primary: {
      DEFAULT: 'hsl(var(--primary))',
      foreground: 'hsl(var(--primary-foreground))',
    },
    secondary: {
      DEFAULT: 'hsl(var(--secondary))',
      foreground: 'hsl(var(--secondary-foreground))',
    },
    destructive: {
      DEFAULT: 'hsl(var(--destructive))',
      foreground: 'hsl(var(--destructive-foreground))',
    },
    muted: {
      DEFAULT: 'hsl(var(--muted))',
      foreground: 'hsl(var(--muted-foreground))',
    },
    accent: {
      DEFAULT: 'hsl(var(--accent))',
      foreground: 'hsl(var(--accent-foreground))',
    },
    popover: {
      DEFAULT: 'hsl(var(--popover))',
      foreground: 'hsl(var(--popover-foreground))',
    },
    card: {
      DEFAULT: 'hsl(var(--card))',
      foreground: 'hsl(var(--card-foreground))',
    },
    sidebar: {
      'DEFAULT': 'hsl(var(--sidebar-background))',
      'foreground': 'hsl(var(--sidebar-foreground))',
      'primary': 'hsl(var(--sidebar-primary))',
      'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
      'accent': 'hsl(var(--sidebar-accent))',
      'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
      'border': 'hsl(var(--sidebar-border))',
      'ring': 'hsl(var(--sidebar-ring))',
    },

    
  neutral: {
    '0': 'var(--neutral-0)',
    '50': 'var(--neutral-50)',
    '100': 'var(--neutral-100)',
    '200': 'var(--neutral-200)',
    '300': 'var(--neutral-300)',
    '400': 'var(--neutral-400)',
    '500': 'var(--neutral-500)',
    '600': 'var(--neutral-600)',
    '700': 'var(--neutral-700)',
    '800': 'var(--neutral-800)',
    '900': 'var(--neutral-900)',
    '950': 'var(--neutral-950)',
    'alpha-24': 'var(--neutral-alpha-24)',
    'alpha-16': 'var(--neutral-alpha-16)',
    'alpha-10': 'var(--neutral-alpha-10)',
  },
  blue: {
    '50': 'var(--blue-50)',
    '100': 'var(--blue-100)',
    '200': 'var(--blue-200)',
    '300': 'var(--blue-300)',
    '400': 'var(--blue-400)',
    '500': 'var(--blue-500)',
    '600': 'var(--blue-600)',
    '700': 'var(--blue-700)',
    '800': 'var(--blue-800)',
    '900': 'var(--blue-900)',
    '950': 'var(--blue-950)',
    'alpha-24': 'var(--blue-alpha-24)',
    'alpha-16': 'var(--blue-alpha-16)',
    'alpha-10': 'var(--blue-alpha-10)',
  },
  orange: {
    '50': 'var(--orange-50)',
    '100': 'var(--orange-100)',
    '200': 'var(--orange-200)',
    '300': 'var(--orange-300)',
    '400': 'var(--orange-400)',
    '500': 'var(--orange-500)',
    '600': 'var(--orange-600)',
    '700': 'var(--orange-700)',
    '800': 'var(--orange-800)',
    '900': 'var(--orange-900)',
    '950': 'var(--orange-950)',
    'alpha-24': 'var(--orange-alpha-24)',
    'alpha-16': 'var(--orange-alpha-16)',
    'alpha-10': 'var(--orange-alpha-10)',
  },
  red: {
    '50': 'var(--red-50)',
    '100': 'var(--red-100)',
    '200': 'var(--red-200)',
    '300': 'var(--red-300)',
    '400': 'var(--red-400)',
    '500': 'var(--red-500)',
    '600': 'var(--red-600)',
    '700': 'var(--red-700)',
    '800': 'var(--red-800)',
    '900': 'var(--red-900)',
    '950': 'var(--red-950)',
    'alpha-24': 'var(--red-alpha-24)',
    'alpha-16': 'var(--red-alpha-16)',
    'alpha-10': 'var(--red-alpha-10)',
  },
  green: {
    '50': 'var(--green-50)',
    '100': 'var(--green-100)',
    '200': 'var(--green-200)',
    '300': 'var(--green-300)',
    '400': 'var(--green-400)',
    '500': 'var(--green-500)',
    '600': 'var(--green-600)',
    '700': 'var(--green-700)',
    '800': 'var(--green-800)',
    '900': 'var(--green-900)',
    '950': 'var(--green-950)',
    'alpha-24': 'var(--green-alpha-24)',
    'alpha-16': 'var(--green-alpha-16)',
    'alpha-10': 'var(--green-alpha-10)',
  },
  yellow: {
    '50': 'var(--yellow-50)',
    '100': 'var(--yellow-100)',
    '200': 'var(--yellow-200)',
    '300': 'var(--yellow-300)',
    '400': 'var(--yellow-400)',
    '500': 'var(--yellow-500)',
    '600': 'var(--yellow-600)',
    '700': 'var(--yellow-700)',
    '800': 'var(--yellow-800)',
    '900': 'var(--yellow-900)',
    '950': 'var(--yellow-950)',
    'alpha-24': 'var(--yellow-alpha-24)',
    'alpha-16': 'var(--yellow-alpha-16)',
    'alpha-10': 'var(--yellow-alpha-10)',
  },
  purple: {
    '50': 'var(--purple-50)',
    '100': 'var(--purple-100)',
    '200': 'var(--purple-200)',
    '300': 'var(--purple-300)',
    '400': 'var(--purple-400)',
    '500': 'var(--purple-500)',
    '600': 'var(--purple-600)',
    '700': 'var(--purple-700)',
    '800': 'var(--purple-800)',
    '900': 'var(--purple-900)',
    '950': 'var(--purple-950)',
    'alpha-24': 'var(--purple-alpha-24)',
    'alpha-16': 'var(--purple-alpha-16)',
    'alpha-10': 'var(--purple-alpha-10)',
  },
  sky: {
    '50': 'var(--sky-50)',
    '100': 'var(--sky-100)',
    '200': 'var(--sky-200)',
    '300': 'var(--sky-300)',
    '400': 'var(--sky-400)',
    '500': 'var(--sky-500)',
    '600': 'var(--sky-600)',
    '700': 'var(--sky-700)',
    '800': 'var(--sky-800)',
    '900': 'var(--sky-900)',
    '950': 'var(--sky-950)',
    'alpha-24': 'var(--sky-alpha-24)',
    'alpha-16': 'var(--sky-alpha-16)',
    'alpha-10': 'var(--sky-alpha-10)',
  },
  pink: {
    '50': 'var(--pink-50)',
    '100': 'var(--pink-100)',
    '200': 'var(--pink-200)',
    '300': 'var(--pink-300)',
    '400': 'var(--pink-400)',
    '500': 'var(--pink-500)',
    '600': 'var(--pink-600)',
    '700': 'var(--pink-700)',
    '800': 'var(--pink-800)',
    '900': 'var(--pink-900)',
    '950': 'var(--pink-950)',
    'alpha-24': 'var(--pink-alpha-24)',
    'alpha-16': 'var(--pink-alpha-16)',
    'alpha-10': 'var(--pink-alpha-10)',
  },
  teal: {
    '50': 'var(--teal-50)',
    '100': 'var(--teal-100)',
    '200': 'var(--teal-200)',
    '300': 'var(--teal-300)',
    '400': 'var(--teal-400)',
    '500': 'var(--teal-500)',
    '600': 'var(--teal-600)',
    '700': 'var(--teal-700)',
    '800': 'var(--teal-800)',
    '900': 'var(--teal-900)',
    '950': 'var(--teal-950)',
    'alpha-24': 'var(--teal-alpha-24)',
    'alpha-16': 'var(--teal-alpha-16)',
    'alpha-10': 'var(--teal-alpha-10)',
  },
  white: {
    DEFAULT: '#fff',
    'alpha-24': 'var(--white-alpha-24)',
    'alpha-16': 'var(--white-alpha-16)',
    'alpha-10': 'var(--white-alpha-10)',
  },
  black: {
    DEFAULT: '#000',
    'alpha-24': 'var(--black-alpha-24)',
    'alpha-16': 'var(--black-alpha-16)',
    'alpha-10': 'var(--black-alpha-10)',
  },
  primarybg: {
    dark: 'var(--primary-dark)',
    darker: 'var(--primary-darker)',
    base: 'var(--primary-base)',
    'alpha-24': 'var(--primary-alpha-24)',
    'alpha-16': 'var(--primary-alpha-16)',
    'alpha-10': 'var(--primary-alpha-10)',
  },
  static: {
    black: 'var(--static-black)',
    white: 'var(--static-white)',
  },
  bg: {
    'strong-950': 'var(--bg-strong-950)',
    'surface-800': 'var(--bg-surface-800)',
    'sub-300': 'var(--bg-sub-300)',
    'soft-200': 'var(--bg-soft-200)',
    'weak-50': 'var(--bg-weak-50)',
    'white-0': 'var(--bg-white-0)',
  },
  text: {
    'strong-950': 'var(--text-strong-950)',
    'sub-600': 'var(--text-sub-600)',
    'soft-400': 'var(--text-soft-400)',
    'disabled-300': 'var(--text-disabled-300)',
    'white-0': 'var(--text-white-0)',
  },
  stroke: {
    'strong-950': 'var(--stroke-strong-950)',
    'sub-300': 'var(--stroke-sub-300)',
    'soft-200': 'var(--stroke-soft-200)',
    'white-0': 'var(--stroke-white-0)',
  },
  faded: {
    dark: 'var(--faded-dark)',
    base: 'var(--faded-base)',
    light: 'var(--faded-light)',
    lighter: 'var(--faded-lighter)',
  },
  information: {
    dark: 'var(--information-dark)',
    base: 'var(--information-base)',
    light: 'var(--information-light)',
    lighter: 'var(--information-lighter)',
  },
  warning: {
    dark: 'var(--warning-dark)',
    base: 'var(--warning-base)',
    light: 'var(--warning-light)',
    lighter: 'var(--warning-lighter)',
  },
  error: {
    dark: 'var(--error-dark)',
    base: 'var(--error-base)',
    light: 'var(--error-light)',
    lighter: 'var(--error-lighter)',
  },
  success: {
    dark: 'var(--success-dark)',
    base: 'var(--success-base)',
    light: 'var(--success-light)',
    lighter: 'var(--success-lighter)',
  },
  away: {
    dark: 'var(--away-dark)',
    base: 'var(--away-base)',
    light: 'var(--away-light)',
    lighter: 'var(--away-lighter)',
  },
  feature: {
    dark: 'var(--feature-dark)',
    base: 'var(--feature-base)',
    light: 'var(--feature-light)',
    lighter: 'var(--feature-lighter)',
  },
  verified: {
    dark: 'var(--verified-dark)',
    base: 'var(--verified-base)',
    light: 'var(--verified-light)',
    lighter: 'var(--verified-lighter)',
  },
  highlighted: {
    dark: 'var(--highlighted-dark)',
    base: 'var(--highlighted-base)',
    light: 'var(--highlighted-light)',
    lighter: 'var(--highlighted-lighter)',
  },
  stable: {
    dark: 'var(--stable-dark)',
    base: 'var(--stable-base)',
    light: 'var(--stable-light)',
    lighter: 'var(--stable-lighter)',
  },
  social: {
    apple: 'var(--social-apple)',
    twitter: 'var(--social-twitter)',
    github: 'var(--social-github)',
    notion: 'var(--social-notion)',
    tidal: 'var(--social-tidal)',
    amazon: 'var(--social-amazon)',
    zendesk: 'var(--social-zendesk)',
  },
  overlay: {
    DEFAULT: 'var(--overlay)',
  },
  transparent: 'transparent',
  current: 'currentColor',
}